<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile><AdditionalIncludeDirectories>$(DependencyDir)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories></ClCompile>
    <Lib><AdditionalLibraryDirectories>$(DependencyDir)\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories></Lib>
    <Link><AdditionalLibraryDirectories>$(DependencyDir)\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories></Link>
  </ItemDefinitionGroup>
</Project>
